services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: goalpocket
      POSTGRES_PASSWORD: capstone123
      POSTGRES_DB: goalpocket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goalpocket -d goalpocket"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: goalpocket-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3002:3002"
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
